### ISSUE TITLE
Speaker Proposal - Ana Balica

### ISSUE THREAD

**Issue by kvbik** [pyvec/cz.pycon.org-2016#25]
cool person [1], speaker at pycon [2], easy to bring her to CZ (lives in london, works for Potato [3]) - sounds good? me and @HonzaKral already told her to speak and she is willing to!

[1] https://twitter.com/anabalica
[2] https://us.pycon.org/2016/speaker/profile/1786/
[3] https://p.ota.to/

**Comment by calmrat** [comment]
Out of curiosity; what might she talk about?

**Comment by honzakral** [comment]
I reached out to ana, will update as soon as I get an answer. I have seen several of her talks and all were really good so I didn't ask when I first talked to her, my bad :)

**Comment by calmrat** [comment]
no worries; i'll search for her and see what talks she's made in the past
as well.

**Comment by honzakral** [comment]
https://www.youtube.com/watch?v=KYG5C1CEkOk
https://www.youtube.com/watch?v=rMn2wC0PuXw

**Comment by honzakral** [comment]
**Mutants for testing**

Mutation testing and Python. [wiki definition] Mutation testing is used to design new software tests and evaluate the quality of existing software tests. Mutation testing involves modifying a program in small ways. Each mutated version is called a mutant and tests detect and reject mutants by causing the behavior of the original version to differ from the mutant.

Key points:
- Test coverage is cool, but doesn’t tell you anything about the quality of tests
- Mutation testing tries to solve this problem applying mutation operations (mutated conditionals, mutated math operations, increments, negated conditionals, etc), reruning the code and observing the results.
- Available tools for Python: mutpy (rarely updated, only Python3)

**Coding&Empathy**

Most of us work in teams, hence human interaction plays a big role in delivering products. Focus of this talk is how empathy can help create better environments and relationships between team members. Heavily applies to open source communities.

Key points:
- As a team we are together, not against each other
- Usage of “we”, rather than “he”, “she”, “they”
- Legacy code and the right mindset to understand the reasons behind some decisions and solutions
- Efficient and non-critisizing "git blame”ing
- Humane code reviews and humane way of accepting feedback (basically don’t be a dick)

**Comment by calmrat** [comment]
She looks good to me! I'm leaning more towards the Coding & Empathy as a keynote, since it's easier to tell stories, connect with a broader portion of the audience and in general, 'call to action'.

**Comment by calmrat** [comment]
@kvbik I would love to have a highly technical keynote from a woman... if she has some 'call to action' or 'highly opinionated technical critique' about Python that aims to make some positive change in the future... PLEASE ask her to keynote... Reach out to her, see what she says... we'll of course pay for her flight/accommodation if she accepts.

**Comment by beatrix-bodo** [comment]
Also Ana Balica is very funny and cool, so I'm certain it would be an
awesome keynote.

**Comment by calmrat** [comment]
Any word back from Ana on interest to keynote?

**Comment by kvbik** [comment]
we just agreed we will talk about pycon.cz tomorrow.

**Comment by calmrat** [comment]
Any updates?

**Comment by kvbik** [comment]
Yeees! Ana would really like to do the Coding & Empathy talk. She'd be willing to keynote this one too!

**Comment by calmrat** [comment]
Sweet! Let's call her ACCEPTED then. Please have her submit the talk abstract, profile, etc to the cfp. Send me her email and I'll follow-up with her about financial aide.
