### ISSUE TITLE
Style Call for Papers form

### ISSUE THREAD

**Issue by beatrix-bodo** [pyvec/cz.pycon.org-2016#39]

**Comment by honzajavorek** [comment]
Mac & Firefox:

<img width="387" alt="screen shot 2016-08-01 at 18 37 35" src="https://cloud.githubusercontent.com/assets/283441/17301546/dbc9d58c-5817-11e6-9393-765d9ef08150.png">

**Comment by honzajavorek** [comment]
Regarding the drop down, it's just a nitpick. If one styles `<select>` by CSS, on Mac it looks weird, because normally drop downs look like this on the platform:

<img width="181" alt="screen shot 2016-08-08 at 09 48 30" src="https://cloud.githubusercontent.com/assets/283441/17472831/713e019e-5d4d-11e6-9d42-15c16bf1dc70.png">

I just checked how [Bootstrap does it](http://v4-alpha.getbootstrap.com/components/forms/) (I thought it does some magic not to disrupt the Mac-native formatting) and it's actually the same 😱 

<img width="802" alt="screen shot 2016-08-08 at 09 50 46" src="https://cloud.githubusercontent.com/assets/283441/17472880/b84f1f96-5d4d-11e6-9713-34864ce22441.png">

So this is a non-issue and feel free to ignore me.

**Comment by tricoder42** [comment]
👍
